#!/usr/bin/env python3
"""
scan_transcript.py — Guild growth-loop foundation (①), bundled best-effort transcript reader.

Reads Claude Code transcripts for a repo and extracts FRICTION signals evolve can propose from:
repeated permission denials, recurring tool errors, rediscovery, repeated commands.

Contract & rationale: see atoms/_signals.md Section F. The CC transcript format is undocumented
and the on-disk dir name is a LOSSY encoding of the cwd, so this is deliberately best-effort:
it matches transcripts by the in-record `cwd` field (which carries the true path), skips
unparseable lines, and exits non-zero with a one-line reason if it cannot read at all — the
caller then degrades to the durable git/CI/gate backbone.

Invoked as ONE bash call (atomic-bash exception):
    python3 <SKILL_DIR>/commands/atoms/scan_transcript.py --repo-cwd <abs-repo-path>

Frequency is measured by DISTINCT session count (>=K), not recency, so there is no time-window
flag: a --since-days filter over the fragile, undocumented transcript timestamps was error-prone
(undated sessions, mixed ISO formats) for no real benefit — the evolve ledger skip-list and the
"already in init/knowledge" filter handle staleness instead.

Read-only. Never writes transcripts. Prints a `>>> RESULT <<<` line then a JSON object.
"""
import argparse, glob, json, os, re, sys
from collections import defaultdict

PROJECTS_DIR = os.path.expanduser("~/.claude/projects")

# --- friction signatures (kill-gate validated) -------------------------------
PERMISSION_RE = re.compile(
    r"Permission to use \w+ with command (.+?) has been denied"
    r"|The user doesn't want to proceed"
)
# tool_result error body -> (label, mapping). Order matters; first match wins.
ERROR_SIGS = [
    (re.compile(r"Cancelled: parallel tool call"),      None),  # DISCOUNT: symptom of a sibling failure
    (re.compile(r"has not been read yet"),              ("edit-before-read", "③ habit")),
    (re.compile(r"Could not resolve to a Repository"),  ("gh-repo-unresolved", "⑥ fact")),
    (re.compile(r"command not found"),                  ("command-not-found", "⑥ fact")),
    (re.compile(r"No such file or directory"),          ("no-such-file", "⑥ fact")),
    (re.compile(r"Caller does not have .* permission"), ("auth-permission", "⑥ fact")),
]
# rediscovery / identity-probe commands (a subset of repeated bash commands)
REDISCOVERY_RE = re.compile(r"^\s*(gh repo view|gh auth (status|switch)|gh api repos/|cat .*config|printenv)")
# Commands Guild's OWN spine mandates be re-run VERBATIM every stage/session (_handoff.md
# Section F: "gh repo view --json nameWithOwner -q .nameWithOwner"; Section H: "printenv
# GLD_UNATTENDED" at every stage start; _preflight.md: "git log --oneline -20";
# _execute_spine.md Step 0/3.5a: the base-branch resolve, the merge-base resolve, the
# HEAD/porcelain readings that bracket the external auditor, the pre-spawn "is there a diff
# to scan" check, and the auditor sub-agent's own `git diff <mb>`). These
# exact invocations are guaranteed to recur >=3 sessions on any actively-used repo and are
# working exactly as designed — flagging them as "rediscovery"/"repeated-cmd" friction
# would pollute evolve's strongest signal source with noise generated by Guild's own
# conventions, not a real repo-specific inefficiency. Anchored to an EXACT match (not a
# prefix) — a prefix match would also swallow legitimate, repo-specific variants that merely
# start the same way (e.g. `git log --oneline --grep=fix -20` or `git log --oneline -- dir/`),
# which are real friction candidates, not Guild's own mandated call.
GUILD_MANDATED_RE = re.compile(
    r"^\s*(gh repo view --json nameWithOwner -q \.nameWithOwner"
    r"|gh repo view --json defaultBranchRef --jq \.defaultBranchRef\.name"
    r"|printenv GLD_UNATTENDED"
    r"|git log --oneline -20"
    r"|git rev-parse HEAD"
    r"|git status --porcelain( -uall)?"
    # the auditor's diff range is a merge-base SHA, so match a SHA-shaped argument only —
    # never a bare `git diff --cached` / `git diff origin/main`, which stay real friction
    r"|git diff (--stat |--numstat |--no-renames |--numstat --no-renames )?[0-9a-f]{7,40}"
    r"|git merge-base \S+ HEAD"
    r"|git rev-parse --abbrev-ref HEAD"
    r"|git branch --list --format='%\(refname:short\)'"
    # the resume-candidate confirmation, `git log <base>..<branch> --oneline`. Looser than the
    # git-diff entry above (both endpoints are repo-specific branch names, so no SHA shape to
    # anchor on) — the cost is that a human's own repeated range-log is also suppressed; the
    # alternative, leaving Guild's per-candidate call unlisted, would emit a friction signal on
    # every resumed execute, which is the noise this whitelist exists to keep out.
    r"|git log \S+\.\.\S+ --oneline"
    r")\s*$")


def text_of(msg):
    c = msg.get("content")
    if isinstance(c, str):
        return c
    parts = []
    if isinstance(c, list):
        for x in c:
            if not isinstance(x, dict):
                continue
            t = x.get("type")
            if t == "text":
                parts.append(x.get("text", ""))
            elif t == "tool_result":
                r = x.get("content")
                if isinstance(r, str):
                    parts.append(r)
                elif isinstance(r, list):
                    parts.append(" ".join(y.get("text", "") for y in r if isinstance(y, dict)))
    return " ".join(parts)


def bash_commands(msg):
    """Yield each Bash tool_use command string in an assistant message."""
    c = msg.get("content")
    if not isinstance(c, list):
        return
    for x in c:
        if isinstance(x, dict) and x.get("type") == "tool_use" and x.get("name") == "Bash":
            cmd = (x.get("input") or {}).get("command")
            if isinstance(cmd, str) and cmd.strip():
                yield cmd.strip()


def file_matches_repo(path, repo_cwd):
    """Best-effort: does any record in this transcript carry cwd == repo_cwd?"""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for i, line in enumerate(fh):
                if i > 400:            # cwd appears early; bound the probe
                    break
                line = line.strip()
                if not line or '"cwd"' not in line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                if d.get("cwd") == repo_cwd:
                    return True
    except OSError:
        return False
    return False


def scan_file(path):
    """Return per-session friction: (perms:set, errors:list, cmds:set) or None if unreadable."""
    perms, errors, cmds = set(), [], set()
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                msg = d.get("message") or {}
                txt = text_of(msg)
                if txt:
                    m = PERMISSION_RE.search(txt)
                    if m:
                        perms.add((m.group(1) or "user-vetoed-edit").strip()[:80])
                    for rx, label in ERROR_SIGS:
                        if rx.search(txt):
                            if label:                       # None => discounted cascade
                                errors.append(label)
                            break
                for cmd in bash_commands(msg):
                    if GUILD_MANDATED_RE.match(cmd):
                        continue
                    # keep the FULL command as the dedup key — truncating here (an
                    # earlier version did `cmd[:80]`) would merge two DISTINCT long
                    # commands that merely share an 80-char prefix into one inflated
                    # signal. Truncate only for display, at output time below.
                    cmds.add(cmd)
    except OSError:
        return None
    return perms, errors, cmds


def rank(sessions):
    if sessions >= 6:
        return "high"
    if sessions >= 3:
        return "med"
    return "low"


def emit(feasibility, degraded, signals, reason=None):
    """Print the one sanctioned RESULT block.

    Emitted on EVERY path, including the ones that find no usable source. `degraded` used to be
    hardcoded False with no code path that could set it True — degradation was signalled only by
    the exit code, which the signal contract never documented, so a caller reading stdout could
    not tell "this repo genuinely has no friction" from "this scan could not see anything."
    Exit codes are unchanged, so a caller that only checks them is unaffected."""
    out = {"feasibility": feasibility, "degraded": degraded, "signals": signals}
    if reason:
        out["reason"] = reason
    print(">>> RESULT <<<")
    print(json.dumps(out, ensure_ascii=False, indent=2))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-cwd", required=True)
    args = ap.parse_args()

    repo_cwd = os.path.abspath(os.path.expanduser(args.repo_cwd))

    if not os.path.isdir(PROJECTS_DIR):
        sys.stderr.write("no ~/.claude/projects dir — transcript source unavailable\n")
        emit("0/0 transcripts parsed", True, [],
             "no ~/.claude/projects directory — transcript source unavailable")
        return 2

    files = glob.glob(os.path.join(PROJECTS_DIR, "*", "*.jsonl"))
    matched = [f for f in files if file_matches_repo(f, repo_cwd)]
    if not matched:
        sys.stderr.write(f"no transcripts matched cwd={repo_cwd} (lossy encoding / none this repo)\n")
        # Not the same as "no friction": a session started in a subdirectory, through a symlinked
        # path, or in a worktree records a different `cwd` and is dropped here silently.
        emit(f"0/{len(files)} transcripts parsed for {repo_cwd}", True, [],
             f"no transcript recorded cwd={repo_cwd} — sessions started from a subdirectory, "
             f"a symlinked path, or a worktree record a different cwd and are not matched")
        return 3

    # aggregate DISTINCT sessions per signal key
    perm_sessions = defaultdict(int)
    err_sessions = defaultdict(lambda: [0, ""])   # label -> [sessions, mapping]
    cmd_sessions = defaultdict(int)
    scanned = 0
    for f in matched:
        r = scan_file(f)
        if r is None:
            continue
        scanned += 1
        perms, errors, cmds = r
        for p in perms:
            perm_sessions[p] += 1
        for label, mapping in set(errors):
            err_sessions[label][0] += 1
            err_sessions[label][1] = mapping
        for c in cmds:
            cmd_sessions[c] += 1

    signals = []
    # `summary`/`mapping` are ASCII English on purpose: this script has no access to the repo's
    # config.language, and its RESULT JSON is consumed by evolve, which renders the human-facing
    # text in config.language (_handoff.md Section K). Emitting a fixed Korean literal here would
    # hardcode one language into a machine payload on an en/ja repo.
    for cmd, n in perm_sessions.items():
        if n >= 2:
            # A generic veto with no captured command is heterogeneous and not mappable to one
            # allow-rule — kill-gate Tier C. Surface it, but cap confidence so it never outranks
            # a specific, actionable signal.
            if cmd == "user-vetoed-edit":
                signals.append({"confidence": "low", "class": "permission",
                                "summary": "generic edit denial (no specific command captured)",
                                "evidence": f"{n} sessions",
                                "sessions": n,
                                "mapping": "noise candidate - heterogeneous, not mappable to a single rule"})
            else:
                signals.append({"confidence": rank(n), "class": "permission",
                                "summary": f"repeatedly denied command: {cmd}", "evidence": f"{n} sessions",
                                "sessions": n, "mapping": "allow-rule (reject if the command is risky)"})
    for label, (n, mapping) in err_sessions.items():
        if n >= 2:
            signals.append({"confidence": rank(n), "class": "tool-error",
                            "summary": f"recurring tool error: {label}", "evidence": f"{n} sessions",
                            "sessions": n, "mapping": mapping})
    for cmd, n in cmd_sessions.items():
        if n >= 3:
            cls = "rediscovery" if REDISCOVERY_RE.match(cmd) else "repeated-cmd"
            signals.append({"confidence": rank(n), "class": cls,
                            "summary": f"repeated command: {cmd[:80]}", "evidence": f"{n} sessions",
                            "sessions": n, "mapping": "⑥ fact / allow-rule"})

    conf_rank = {"high": 3, "med": 2, "low": 1}
    signals.sort(key=lambda s: (conf_rank.get(s["confidence"], 0), s["sessions"]), reverse=True)
    # Partial parse is real degradation: scan_file returns None for a transcript it cannot read,
    # so the signal counts below are computed over fewer sessions than were matched, and every
    # frequency threshold (≥2 / ≥3 sessions) is correspondingly under-counted.
    unreadable = len(matched) - scanned
    reason = None
    if unreadable > 0:
        reason = (f"{unreadable} of {len(matched)} matched transcripts were unreadable — "
                  f"session counts are a lower bound, so a real signal may sit below threshold")
    emit(f"{scanned}/{len(matched)} transcripts parsed for {repo_cwd}",
         unreadable > 0, signals, reason)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:                       # never crash the caller; degrade
        sys.stderr.write(f"scan_transcript failed: {e}\n")
        try:
            emit("0/0 transcripts parsed", True, [], f"scan aborted: {e}")
        except Exception:
            pass
        sys.exit(1)
